export const LOAD_USER_DATA = 'LOAD_USER_DATA';
export const IS_DATA_LOADED = 'IS_DATA_LOADED';
export const HEALTH_WIDGET_BENEFITS = 'HEALTH_WIDGET_BENEFITS';
export const HEALTH_WIDGET_CLAIMS = 'HEALTH_WIDGET_CLAIMS';
export const HOME_WIDGET_CARE = 'HOME_WIDGET_CARE';
export const HOME_WIDGET_TODAY = 'HOME_WIDGET_TODAY';
export const HOME_WIDGET_WELLNESS = 'HOME_WIDGET_WELLNESS';
export const HOME_WIDGET_HEALTH = 'HOME_WIDGET_HEALTH'; 
